(setf *title* "lrw04 的博客")
(setf *latex-macros* '(("\\Gal" 0 "\\operatorname{Gal}")
                       ("\\tr" 0 "\\operatorname{tr}")
                       ("\\GL" 0 "\\operatorname{GL}")
                       ("\\SL" 0 "\\operatorname{SL}")
                       ("\\PSL" 0 "\\operatorname{PSL}")
                       ("\\SO" 0 "\\operatorname{SO}")
                       ("\\SU" 0 "\\operatorname{SU}")
                       ("\\im" 0 "\\operatorname{im}")
                       ("\\cof" 0 "\\operatorname{cof}")
                       ("\\End" 0 "\\operatorname{End}")
                       ("\\Tor" 0 "\\operatorname{Tor}")
                       ("\\rk" 0 "\\operatorname{rk}")
                       ("\\Hom" 0 "\\operatorname{Hom}")
                       ("\\diag" 0 "\\operatorname{diag}")
                       ("\\vspan" 0 "\\operatorname{span}")
                       ("\\lcm" 0 "\\operatorname{lcm}")
                       ("\\id" 0 "\\operatorname{id}")
                       ("\\Ab" 0 "\\textsf{Ab}")
                       ("\\Fld" 0 "\\textsf{Fld}")
                       ("\\Mod" 1 "#1\\textsf{-Mod}")
                       ("\\Grp" 0 "\\textsf{Grp}")
                       ("\\dSet" 1 "#1\\textsf{-Set}")
                       ("\\Set" 0 "\\textsf{Set}")
                       ("\\SetStar" 0 "\\textsf{Set*}")
                       ("\\Vect" 1 "#1\\textsf{-Vect}")
                       ("\\Alg" 1 "#1\\textsf{-Alg}")
                       ("\\Ring" 0 "\\textsf{Ring}")
                       ("\\R" 0 "\\mathbb{R}")
                       ("\\C" 0 "\\mathbb{C}")
                       ("\\N" 0 "\\mathbb{N}")
                       ("\\Z" 0 "\\mathbb{Z}")
                       ("\\Q" 0 "\\mathbb{Q}")
                       ("\\F" 0 "\\mathbb{F}")
                       ("\\sfC" 0 "\\mathsf{C}")
                       ("\\vphi" 0 "\\varphi")))
(setf *character-replacements* '((#\。 . #\．)))
(setf *tag-titles* '(("probsel" . "题选")
                     ("artin" . "Artin 做法")
                     ("hsmath" . "高中数学备课")))
(setf *preamble* 
      (alexandria:read-file-into-string (format nil "~a/preamble.tex" *repo*)))
